### ISSUE TITLE
Unhelpful Error Code

### ISSUE THREAD

**Issue by SamBobBarnes** [mini-bomba/create-github-release#5] opened 2023-11-30 14:52 UTC
I am getting the error 
`Error: ❌ Command ['git', 'tag', '-f', '1.8.23 ', '***'] returned with non-zero exit code!`
which is unhelpful bc there is no indication of what went wrong. It would be nice to at least return the error code.

**Comment by mini-bomba** [comment] 2023-11-30 14:57
Isn't the output from git present in the logs already?

**Comment by mini-bomba** [comment] 2023-12-02 17:39
Closing as output from git should already be present in the logs, so returning any error code would be redundant. (and would provide less information than the logs)
If you believe this error was caused by a bug in my code, please open another issue and provide logs of the gh actions run. (or at least logs from this action and any context about the environment it is being run in)

**Closed as not planned by mini-bomba** 2023-12-02 17:39 UTC

**Comment by NorthernMan54** [comment] 2024-11-22 16:21
FYI - Ran into a similar issue, and found that this occurred as I had not checked out the REPO prior to using this.  Kinda stupid, but as I was jumping between different actions for release, missed it.

The fix

```
- uses: actions/checkout@v4
```
